### ISSUE TITLE
Gameplay Issue: Score value is excessive when passing a pillar.

### ISSUE THREAD

**Issue by Appl3Kitti3** [COMP2522/project-jencm#25]
for(Pipe pipe: pipes){
        if(!pipe.isPass() && p1.getX() >pipe.getX() + pipe.getWidth()){
          pipe.setPass(true);
          score++;
        }
      }
      
      Loop of score increment.
      You can either implement a function where if the pipe passes, increment the score.

**Comment by noorksangha** [comment]
Fixed score issue
